name: happy-commit
on:
  - pull_request

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  happy:
    runs-on: ubuntu-latest
    name: happy
    continue-on-error: true
    steps:
      - uses: kitsuyui/happy-commit@v0.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
